version: '3.8'

services:
  svr_n8n:
    image: n8nio/n8n
    container_name: cont_n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=http://svr_n8n:5678 # Sử dụng tên service nội bộ
      - WEBHOOK_URL=http://svr_n8n:5678       # Sử dụng tên service nội bộ
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_MCP_ENABLED=true
      - N8N_MCP_MODE=server
      # Không cần thiết lập N8N_HOST và WEBHOOK_URL với IP bên ngoài khi dùng ngrok
      # - N8N_HOST=${EXTERNAL_IP}
      # - WEBHOOK_URL=${EXTERNAL_IP}
    ports:
      - "5678:5678" # N8n mặc định chạy trên cổng 5678 bên trong container
    volumes:
      - ${CURR_DIR}/vol_n8n:/home/node/.n8n

  ngrok:
    image: ngrok/ngrok
    container_name: cont_ngrok
    environment:
      NGROK_AUTHTOKEN: your_authtoken_here # THAY THẾ BẰNG cr_2xUfBB7a6VLxegoEN4ZY3DET3hs
    ports:
      - "4040:4040" # Giao diện web ngrok (tùy chọn)
    command:
      - "http"
      - "svr_n8n:5678" # Forward đến service svr_n8n trên cổng 5678
    depends_on:
      - svr_n8n
